import os
import uuid
from common.celery_app import celery
from prometheus_client import Counter

# metric
reports_counter = Counter('reports_generated_total', 'Number of reports generated')

OUTPUT_DIR = os.getenv('REPORT_OUTPUT_PATH', '/app/report_output')


@celery.task
def generate_report(property_id: str):
    """Simulate PDF report generation by writing a placeholder file."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    try:
        os.chmod(OUTPUT_DIR, 0o777)
    except Exception:
        pass
    task_id = str(uuid.uuid4())
    filename = f"report_{task_id}.pdf"
    path = os.path.join(OUTPUT_DIR, filename)
    # create a minimal PDF using reportlab
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
        c = canvas.Canvas(path, pagesize=letter)
        c.drawString(72, 720, f"Report for property {property_id}")
        c.drawString(72, 700, f"Generated by task {task_id}")
        c.save()
    except Exception:
        # fallback to text file if reportlab not available
        with open(path, 'w') as f:
            f.write(f"Report for property {property_id}\nGenerated by task {task_id}\n")
    reports_counter.inc()
    return {"task_id": task_id, "path": path}
